#!/bin/bash

echo powersave | sudo tee /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo powersave | sudo tee /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo powersave | sudo tee /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo powersave | sudo tee /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
xfconf-query --channel=xfwm4 --property=/general/use_compositing --set=true
sudo sysctl vm.swappiness=60

