#!/bin/bash

sudo apt-get install php7.0-curl php7.0-json php7.0-cgi
sudo systemctl enable apache2
sudo apt-get install mysql-server
sudo apt-get install php7.0 php-pear libapache2-mod-php7.0 php7.0-mysql
sudo apt-get install php7.0-curl php7.0-json php7.0-cgi phpmyadmin
sudo service apache2 restart

